export const courts = [
  {
    id: "1",
    name: "Zilker Park Courts",
    address: "2100 Barton Springs Rd, Austin, TX 78704",
    image: "/placeholder.svg?height=400&width=600&text=Zilker+Park+Courts",
    rating: 4.7,
    reviewCount: 128,
    amenities: ["Outdoor", "Lights", "Water Fountain", "Parking", "Restrooms"],
  },
  {
    id: "2",
    name: "Metz Recreation Center",
    address: "2407 Canterbury St, Austin, TX 78702",
    image: "/placeholder.svg?height=400&width=600&text=Metz+Recreation+Center",
    rating: 4.5,
    reviewCount: 87,
    amenities: ["Indoor", "Air Conditioning", "Locker Room", "Water Fountain"],
  },
  {
    id: "3",
    name: "Pease District Park",
    address: "1100 Kingsbury St, Austin, TX 78705",
    image: "/placeholder.svg?height=400&width=600&text=Pease+District+Park",
    rating: 4.2,
    reviewCount: 65,
    amenities: ["Outdoor", "Parking", "Shaded Area"],
  },
  {
    id: "4",
    name: "Austin Recreation Center",
    address: "1301 Shoal Creek Blvd, Austin, TX 78701",
    image: "/placeholder.svg?height=400&width=600&text=Austin+Recreation+Center",
    rating: 4.8,
    reviewCount: 142,
    amenities: ["Indoor", "Air Conditioning", "Locker Room", "Pro Shop", "Gym"],
  },
  {
    id: "5",
    name: "Bartholomew District Park",
    address: "1730 Greenbrook Pkwy, Austin, TX 78723",
    image: "/placeholder.svg?height=400&width=600&text=Bartholomew+District+Park",
    rating: 4.3,
    reviewCount: 76,
    amenities: ["Outdoor", "Lights", "Water Fountain", "Parking"],
  },
  {
    id: "6",
    name: "Northwest Recreation Center",
    address: "2913 Northland Dr, Austin, TX 78757",
    image: "/placeholder.svg?height=400&width=600&text=Northwest+Recreation+Center",
    rating: 4.6,
    reviewCount: 93,
    amenities: ["Indoor", "Air Conditioning", "Locker Room", "Water Fountain"],
  },
]

export const reviews = [
  {
    id: "101",
    courtId: "1",
    userName: "Michael J.",
    userImage: "/placeholder.svg?height=50&width=50&text=MJ",
    rating: 5,
    date: "March 2, 2025",
    text: "Great courts with plenty of space. The surface is well-maintained and there are usually people to play with on weekends. The lights make evening games possible, which is awesome during summer.",
  },
  {
    id: "102",
    courtId: "1",
    userName: "Sarah T.",
    userImage: "/placeholder.svg?height=50&width=50&text=ST",
    rating: 4,
    date: "February 15, 2025",
    text: "I love playing here! The courts are in good condition and there's usually a good crowd. Only giving 4 stars because the water fountain was broken last time I visited.",
  },
  {
    id: "103",
    courtId: "1",
    userName: "James L.",
    userImage: "/placeholder.svg?height=50&width=50&text=JL",
    rating: 5,
    date: "January 28, 2025",
    text: "Best outdoor courts in Austin! Great atmosphere and the lights make it perfect for evening games. Highly recommend!",
  },
  {
    id: "201",
    courtId: "2",
    userName: "Kobe W.",
    userImage: "/placeholder.svg?height=50&width=50&text=KW",
    rating: 5,
    date: "March 5, 2025",
    text: "Indoor courts are perfect for hot summer days. The AC works great and the staff is friendly. Courts are well-maintained.",
  },
  {
    id: "202",
    courtId: "2",
    userName: "Lisa M.",
    userImage: "/placeholder.svg?height=50&width=50&text=LM",
    rating: 4,
    date: "February 20, 2025",
    text: "Good indoor option. Can get crowded on weekends but weekday mornings are usually empty. Locker rooms are clean.",
  },
]

